### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Defman21** [Komodo/Komodo-TypeScript-LSP#1]
Komodo 11.1. I've tried to install it using Commando as well as simply dropping the xpi into Komodo.

```
[2018-06-26 01:14:37,285] [ERROR] console-logger: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Jun 26 2018 01:14:36 GMT+0300 (Russia TZ 2 Standard Time)
Full Message: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.isDirectory] (0) in resource://gre/modules/addons/XPIProvider.jsm:1297
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm", line 1297, in 

2018-06-26 01:20:13,835] [ERROR] commando-scope-packages: Unable to install TypeScript-LSP: -4
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:411:27
    this._addonInstallListener.onInstallFailed@chrome://scope-packages/content/packages.js:1134:13
    AMI_callInstallListeners@resource://gre/modules/AddonManager.jsm:1493:15
    AMP_callInstallListeners@resource://gre/modules/AddonManager.jsm:2449:1
    AI_startInstall/<@resource://gre/modules/addons/XPIProvider.jsm:5845:1
    Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:868:21
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744:7

```

Other add-ons (e.g. Xemmet) installs fine.

**Comment by Naatan** [comment]
I think this is a general random error with the package installer, I've seen it from time to time. Could you try it a few times?

I've tried this addon on windows and it worked fine for me.

**Comment by Defman21** [comment]
Only the installation is broken. The add-on works fine :)

**Comment by Naatan** [comment]
How'd you get it installed?

**Comment by Defman21** [comment]
Downloaded the xpi and unpacked it to XRE/extensions.

**Comment by Naatan** [comment]
@cgchoffman can you repro on windows?

**Comment by th3coop** [comment]
Yep.
```
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Wed Jul 18 2018 15:17:06 GMT-0700 (Pacific Standard Time)
Full Message: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.isDirectory] (0) in resource://gre/modules/addons/XPIProvider.jsm:1297
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm", line 1297, in 

[2018-07-18 15:18:16,137] [ERROR] commando-scope-packages: Unable to install TypeScript-LSP: -4
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:411:27
    this._addonInstallListener.onInstallFailed@chrome://scope-packages/content/packages.js:1134:13
    AMI_callInstallListeners@resource://gre/modules/AddonManager.jsm:1493:15
    AMP_callInstallListeners@resource://gre/modules/AddonManager.jsm:2449:1
    AI_startInstall/<@resource://gre/modules/addons/XPIProvider.jsm:5845:1
    Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:868:21
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744:7

[2018-07-18 15:18:16,388] [ERROR] commando-scope-packages: Unable to install TypeScript-LSP: -4
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:411:27
    this._addonInstallListener.onInstallFailed@chrome://scope-packages/content/packages.js:1134:13
    AMI_callInstallListeners@resource://gre/modules/AddonManager.jsm:1493:15
    AMP_callInstallListeners@resource://gre/modules/AddonManager.jsm:2449:1
    AI_startInstall/<@resource://gre/modules/addons/XPIProvider.jsm:5845:1
    Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:868:21
    this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744:7

```

**Comment by Naatan** [comment]
Thanks. Opened a bug on the KomodoEdit repo (we don't really reference this one, as you probably noticed).
